### ISSUE TITLE
Implementation using integer primary key

### ISSUE THREAD

**Issue by charanraj-golla** [MatthewRudolph/Airy#1]
Hi Matthew, thanks for the efforts you took to make this library.
I am working on an application which uses Nhibernate for DAL.  I wanted to use ASP.NET One Identity with integer primary key. 
I was trying to use this library and was implementing it in similar lines (regarding architecture) to the solution provided over here -> http://weblogs.asp.net/imranbaloch/a-sample-of-onion-architecture-with-asp-net-identity
Just wanted to know if there was a less complicated way of achieving this.

**Comment by MatthewRudolph** [comment]
Hi Charan,

The current sample is just the default Visual Studio ASP.Net web template when local accounts are selected as the authentication type, with the minimum changes required to switch it to using my airy NHibernate identity library.
In real life projects I actually use Autofac as my IoC of choice to build and inject the dependencies much like the onion architecture.  Although I do not goes as far as removing the dependencies on ASP.Net Identity Core and OWIN from my web project into separate project that is certainly possible you just need to create your own interfaces to use.

I usually use Guids as a primary key, but I can create a new sample with the minimum required dependencies and code that uses integers as the primary keys and Autofac for the IoC container and dependency injection, would that help?

I am away for a long weekend from tomorrow, and have work commitments as well so I won’t have a chance to do this until next week, or the week after, sorry.

As soon I have time I’ll also add some details to the getting started section too, to make it easy for you to get started with it in your own project.

**Comment by charanraj-golla** [comment]
It would be very helpful if you could provide a sample. Hope you find some time to implement this. Thanks for helping !

**Comment by MatthewRudolph** [comment]
Added [sample website](https://github.com/MatthewRudolph/Airy-Identity-Nhibernate/tree/master/samples/Dematt.Airy.Sample.IntWebSite) using int for all primary keys for the identity objects.

Also updated the [ReadMe](https://github.com/MatthewRudolph/Airy-Identity-Nhibernate/blob/master/README.md) documentation with details of how to configure the identity entities with your choice of primary key type.

This [commit](https://github.com/MatthewRudolph/Airy-Identity-Nhibernate/commit/f260ebb729e7d7bc1a443941ac9799286ea1fff7) shows the changes required to the default Visual Studio ASP.NET MVC with Individual User Accounts template to swith it from the Enity Framework to NHibernate.
